# Generated by Django 5.1 on 2025-02-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_crfeated_date_comment_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approve_comment',
            new_name='approved_comment',
        ),
    ]
